---
title: 'Simulation: Sample DAGs with local structure'
author: "Vera Kvisgaard"
date: "2024-05-24"
output:
  html_document: 
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	cache = TRUE,
	fig.show = "hold",
	results = "hold"
)
```


# Prep
```{r message=FALSE}
library(doSNOW)
library(foreach)
library(BiDAG)
library(ldags)
library(ggplot2)
library(dplyr)
here::i_am("./simulations/bn/simulation_bn.Rmd")
simpar <- expand.grid(list(method = c("ldag", "tree", "dag"),
                           N = c(100, 1000, 10000),
                           r = 1:30))
doRun <- F
```





# Evaluate 

## Define routines for evaluating the sampled DAGs.
```{r}
library(ggplot2)
library(dplyr)



```

```{r}
eval_files <- function(filepaths, bnname) {
  
  indx <- grepl(bnname, filepaths, T)
  if (!all(indx)) stop("All files do not match bnname.")
  
  bn <- readRDS(here::here("./data/", paste0(bnname, ".rds")))
  n  <-  length(bn)
  dindx <- diag(n) == 1
  dag  <- bnlearn::amat(bn)[!dindx]
  dmat <- bida:::descendants(bn)[!dindx]
  
  res <- foreach(f = filepaths, 
                 .combine  = "rbind",
                 .packages = "Matrix") %dopar% eval_MCMCchain(f, seq(200), dag, dmat, n)
  

}

eval_MCMCchain <- function(f, burninsamples, dag, dmat, n, verbose = T) {
 # if (verbose) cat(f)
  MCMCchain <- readRDS(f)$smpl
  dindx <- diag(n) == 1
  dags <- lapply(MCMCchain$traceadd$incidence[-burninsamples], as.matrix)
  
  # list unique DAGs
  u    <- unique(dags)
  support  <- bida:::rowsum_fast(rep(1/length(dags), length(dags)), dags, u)
  dags <- u 
  dmats <- lapply(dags, bida:::descendants)
  
  edgep <- Reduce("+", Map("*", dags, support))[!dindx]
  ancp  <- Reduce("+", Map("*", dmats, support))[!dindx]
  
  res <- matrix(nrow = 2, ncol = 3)
  colnames(res) <- c("TPR", "FPR", "avgppv")
  rownames(res) <- c("edgep", "ancp")

  # edge probs
  n1 <- sum(dag)
  res[1, 1] <- sum(edgep[dag == 1])/n1
  res[1, 2] <- sum(edgeps[dag == 0])/(n**2-n-n1)
  res[1, 3] <- compute_avgppv(edgep, dag)
  
  # arp
  n1 <- sum(dmat)
  probs <- Reduce("+", Map("*", dmats, support))[!dindx]
  res[2, 1] <- sum(ancp[dmat == 1])/n1
  res[2, 2] <- sum(ancp[dmat == 0])/(n**2-n-n1)
  res[2, 3] <- compute_avgppv(ancp, dmat)
  
  list(edgep = edgep, 
       rates = res, 
       pr = compute_prec_recall(ancp, dmat),
       toc = as.matrix(attr(MCMCchain, "toc")))
  
}

compute_prec_recall <- function(x, y) {
  indx <- order(x, decreasing = TRUE)
  tp   <- cumsum(y[indx])
  cbind(x = x[indx], TPR = tp/sum(y), PPV = tp/seq_along(x))
}

compute_avgppv <- function(x, y) {
  
  indx <- order(x, decreasing = TRUE)
  tp   <- cumsum(y[indx])
  pp   <- seq_along(x)
  
  dups <- duplicated(x[indx], fromLast = TRUE)
  #cbind(dups, x[indx], c(y[indx]), tp, pp)
  w <- c(tp[1], diff(tp[!dups]))/tp[length(x)]
  sum(w*tp[!dups]/pp[!dups])
}
res_to_df <- function(res, filepaths) {
  
  tmp <- stringr::str_split(filepaths, ".+MCMCchains/|_|.rds", simplify = F)
  par <- data.frame(do.call(rbind, tmp)[, 2:7])
  colnames(par) <- c("network", "algo", "struct", "N", "epf", "r")
  par$N <- factor(par$N, c("N100", "N300", "N1000", "N3000", "N10000"))
  
  tmp <- do.call(rbind, res)
  if (nrow(tmp) == length(filepaths)) {
    return(cbind(par, tmp))
  } else {
    nrows <- vapply(res, nrow, integer(1))
    df <- cbind(par[rep.int(seq_along(filepaths), nrows), ], tmp)
    df$name <- rownames(tmp)
    return(df)
  }
}

plot_box_plot <- function(df, var, title = "") {
  ggplot(df, aes(N, y = !! sym(var), fill = struct)) +
   facet_grid(algo+name~network+epf) +
   geom_boxplot() +
   ggtitle(title)      
}
plot_prec_recall <- function(df, title = "") {
   ggplot(df, aes(TPR, PPV, group = r)) +
    facet_grid(algo+struct+epf~network+N) +
    geom_line() +
    ggtitle(title)
}


```

```{r}
cl <- makeCluster(6, type = "SOCK", outfile = "")
clusterExport(cl, c("eval_MCMCchain", "compute_avgppv", "compute_prec_recall"))
registerDoSNOW(cl)
```

```{r}
bnname <- "LDAG10"
filepaths <- list.files(here::here("./simulations/bn/MCMCchains"), 
                        pattern = sprintf("%s_partition", bnname), full.names = T)
filepaths <- filepaths[!grepl("N100_", filepaths)]
tmp <- eval_files(filepaths, bnname) 
```

```{r}
df <- res_to_df(tmp[, 1], filepaths)
plot_box_plot(df, "TPR")
plot_box_plot(df, "FPR")
plot_box_plot(df, "avgppv")
```

```{r}
df <- res_to_df(tmp[, 2], filepaths)
plot_prec_recall(df)
```

```{r }
df <- res_to_df(tmp[, 3], filepaths)
plot_box_plot(df, "tmp")
```



```{r, cache = T}



```


## Labeled DAG with 10 nodes
### Edge penalization factor: 2 (default value in `BiDAG`)
```{r}
res <- eval("LDAG10", "epf1")
res <- eval("LDAG10", "epf2")
res <- eval("LDAG10", "epf4")
```

### Edge penalization factor: 4
```{r}
eval("LDAG10", "epf4")
```

## Sachs (10 variables, all with 3 categories (LOW, AVG, HIGH))
```{r}
eval("sachs", "epf2")
```

## Child (20 variables, 2-6 categories, 3 in average)
```{r}
eval("child", "epf2")
```